name: Terraform CI/CD

on:
  push:
    branches:
      - dev  
  workflow_dispatch:
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências Python (black, isort)
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Configurar AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Lambda Zips
      run: python scripts/build_lambda.py
      working-directory: ${{ github.workspace }}
    
    - name: Init Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Validar Terraform
      working-directory: ./terraform
      run: terraform validate
    
    - name: Terraform Format
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform Format Python code Black
      run: black lambda/

    - name: Terraform Format Python code isort
      run: isort lambda/

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan
      continue-on-error: false

    - name: Terraform Apply (Deploy)
      working-directory: ./terraform
      run: terraform apply -auto-approve

      
    
