variable "api_name" {}
variable "function_name" {}
variable "http_method" {}
variable "region" {}
variable "environment" {}
variable "lambda_invoke_arn_get" {}
variable "lambda_function_arn" {}
variable "lambda_function_name_get" {}
variable "cognito_user_pool_arn" {}
